title: ðŸ§— ClimbingLand
author: ""
email: info@climbing.land
description: "Tutte le migliori informazioni per scalare"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://climbing.land" # the base hostname & protocol for your site, e.g. http://example.com
lang: it

header_pages:
  - guides.md
  - instructors.md
  - gyms.md
  - index.md

permalink: /:categories/:title
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  gyms:
    output: true
  users:
    output: true

new_user_form: https://airtable.com/shrRfAfsHz2K1VeAB
new_gym_form: https://airtable.com/shrfkSjZ7oK0yS1TV

instagram_username: climbing.land
